name=OwiBusPHY
version=1.0.0
author=Ivaylo Panov
maintainer=Ivaylo Panov
sentence=AVR interrupt based OwiBus physical layer communication library.
paragraph=Provides low level OwiBus PHY communication using pin change interrupts and Timer2 on AVR Arduino boards.
category=Communication
url=
architectures=avr
